add update and remove which can use limit and order_by
rbock/sqlpp11-connector-mysql pull request #71
Opened 2021-06-30 03:16 UTC by ZerQAQ

see https://github.com/rbock/sqlpp11/issues/370

2021-06-30 05:27 UTC, rbock requested changes
Thanks for the pull request.

2021-06-30 05:27 UTC, rbock commented on include/sqlpp11/mysql/remove.h
> +    struct remove_t : public statement_name_t<remove_name_t>
Can't you just use `sqlpp::remove_t` (same question for `update_t`)?

2021-06-30 05:27 UTC, rbock commented on include/sqlpp11/mysql/remove.h
> +    using blank_remove_t = statement_t<Database, remove_t, no_from_t, no_using_t, no_where_t<true>, no_limit_t, no_order_by_t>;
According to mysql's documentation, `ORDER BY` has to come first.

Please add at least one test for remove and another for update.

2021-07-02 17:53 UTC, rbock requested changes

2021-07-02 17:53 UTC, rbock commented on include/sqlpp11/mysql/remove.h
> +  namespace mysql{
Is this still needed?

2021-07-02 17:53 UTC, rbock commented on include/sqlpp11/mysql/remove.h
> +#include <sqlpp11/where.h>
The includes need to be cleaned up, too.

Try compiling just the header, to see what is missing (and what is superfluous(.

2021-07-02 17:53 UTC, rbock commented on include/sqlpp11/mysql/update.h
> +    struct update_name_t
Same in this file.

2021-07-06 18:07 UTC, rbock commented on include/sqlpp11/mysql/remove.h
> +  namespace mysql{
To clarify:
`remove_name_t` and its serializer are not needed, I think. Please remove them (or explain why it is needed).

Similarly for update.

Thanks.

2021-07-26 10:55 UTC, zhengminlai commented
Hi, can the pull request be merged?

2021-07-26 19:51 UTC, rbock commented
As far as I can tell, `remove_name_t` and `update_name_t` are superfluous and still present. Otherwise, this looks OK to me.

2021-11-06 16:47 UTC, rbock commented
Implemented on develop of sqlpp11.

2021-11-06 16:47 UTC, closed without merging